application: eliasnaur-talks
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: present/static/favicon.ico
  upload: present/static/favicon.ico
  secure: always
- url: /static
  static_dir: present/static
  application_readable: true
  secure: always
- url: /.*
  script: _go_app
  secure: always

# nobuild_files is a regexp that identifies which files to not build.  It
# is useful for embedding static assets like code snippets and preventing
# them from producing build errors for your project.
#nobuild_files: [path regexp for talk materials]
